apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - image: node
        name: frontend
        resources:
          requests:
            cpu: 60m
            memory: 64Mi
          limits:
            cpu: 120m
            memory: 128Mi