apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: frontend
  namespace: dev
spec:
  ports:
  - name: node
    port: 80
    targetPort: 3010
  - name: web
    port: 80
    $patch: delete
  selector:
    app: web