namespace: dev
resources:
- ../../base

patchesStrategicMerge:
- service.yaml
- mem.yaml

images:
- name: node
  newName: aade/node
  newTag: v1.0.0-dev

replicas:
- count: 2
  name: frontend

namePrefix: dev-

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.10-0-10-13.sslip.io
  target:
    kind: Ingress
    name: ingress-myservice
- path: node-selector.yaml
  target:
    kind: Deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
