---
namespace: dev
resources:
  - ../../base

patchesStrategicMerge:
- service.yaml

images:
- name: nginx
  newName: aade/node
  newTag: v1.0.0-dev

replicas:
- name: frontend
  count: 1

namePrefix: dev-

patches:
  - target:
      kind: Ingress
      name: ingress-myservice
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.10-0-10-13.sslip.io
  - path: node-selector.yaml
    target:
      kind: Deployment