apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - image: node
        name: frontend
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 40m
            memory: 64Mi